-- require("codesnap").setup({
--     mac_window_bar = true,
--     bg_color = "#111111",
--     code_font_family = "Fantasque Sans Mono",
--     watermark = "",
--     -- save_path = "/Users/jamiegibney/Documents/nvim captures/foo.png",
-- })
