-- Unmapping these may be temporary, but is currently useful to prevent accidents on the new keyboard :)

vim.keymap.set("i", "<F1>", "")
vim.keymap.set("i", "<F2>", "")
vim.keymap.set("i", "<F3>", "")
vim.keymap.set("i", "<F4>", "")
vim.keymap.set("i", "<F5>", "")
vim.keymap.set("i", "<F6>", "")
vim.keymap.set("i", "<F7>", "")
vim.keymap.set("i", "<F8>", "")
vim.keymap.set("i", "<F9>", "")
vim.keymap.set("i", "<F10>", "")

vim.keymap.set("n", "<F1>", "")
vim.keymap.set("n", "<F2>", "")
vim.keymap.set("n", "<F3>", "")
vim.keymap.set("n", "<F4>", "")
vim.keymap.set("n", "<F5>", "")
vim.keymap.set("n", "<F6>", "")
vim.keymap.set("n", "<F7>", "")
vim.keymap.set("n", "<F8>", "")
vim.keymap.set("n", "<F9>", "")
vim.keymap.set("n", "<F10>", "")
